# Uncomment the next line to define a global platform for your project


platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!


target 'HyCycleViewDemo' do

pod 'MJRefresh'
pod 'FDFullscreenPopGesture'

end
